### ISSUE TITLE
Double page mode bugs

### ISSUE THREAD

**Issue by rathsky** [benoit-pierre/mcomix#2] opened 2015-09-21 14:40 UTC
Double page mode together with "show only one page where appropriate" has been bugged for quite a while now, eg:

1) Backwards from wide to two narrow images only shows the first narrow one. However, the second one is still somehow counted as having been shown, as MComix will omit one page when (further) moving backwards.

(Eg: 1n, 2n, 3w. Start at 3w, two-page step backwards: Only 2n show. Another two-page step backwards: MComix tries to open previous folder/archive. This also applies when there's more than one preceding pages.)

2) Changing the "show only one page" option does not update the current view when it would be appropriate.

**Comment by benoit-pierre** [comment] 2015-09-21 16:59
Please open a bug on the [official bug tracker](https://sourceforge.net/p/mcomix/_list/tickets).

Don't forget to mention the version your using.

**Comment by benoit-pierre** [comment] 2015-09-21 22:14
Both regressions are  fixed in https://github.com/benoit-pierre/mcomix/tree/double-page-mode-bug-fixes. Feedback welcome if you have time to test it.

**Comment by rathsky** [comment] 2015-09-22 01:37
Appears to work as intended now again, thanks.

(Both my reports were with mcomix from your master branch on Arch Linux, ie. latest python etc.)

**Comment by rathsky** [comment] 2015-09-22 12:54
Hm, there is one more issue though: Suppose you have 1n, 2n, 3n, 4w and are at 1. Advancing should display 2 and 3, but only shows 3. This doesn't occur in the opposite direction.

**Comment by benoit-pierre** [comment] 2015-09-22 14:26
No, if you have "Show only one page were appropriate" set to "Only for wide images", and the archive is as you describe, then:
- on the first page, 1+2 are displayed
- advancing with "Next page" will move forward 2 pages to 3, only 3 is shown because 4 is a virtual double page
- if instead you advance with "Next page (always one page)", then you move to 2, and 2+3 are shown

**Comment by rathsky** [comment] 2015-09-23 02:41
But this isn't consistent with the behavior in the backwards direction, ie.:
"1w 2n 3n 4n": Start at 3+4. Backwards moves to 2+3.
"1n 2n 3n 4w": Start at 1+2. Forward moves to 3.

IMHO forward should also move to 2+3. MComix is in double-page mode, after all.

**Comment by benoit-pierre** [comment] 2015-09-23 13:35
Are you purposely using different samples? Because, assuming again "Show only one page were appropriate" is set to "Only for wide images", the results are expected.

Also, if you think about

**Comment by rathsky** [comment] 2015-09-23 13:38
No, I'm really not. If you want to use a single sample, eg.:
1n 2w 3n 4n 5n 6w 7n
(movement back & forth accordingly)

**Comment by benoit-pierre** [comment] 2015-09-23 14:06
OK, here a small script to create sample archives with a specific layout:

```python
#!/usr/bin/env python2

from PIL import Image, ImageDraw

import tempfile
import shutil
import subprocess
import sys


WHITE = (255, 255, 255)
BLACK = (  0,   0,   0)

archive = sys.argv[1]
layout = sys.argv[2]

tmpdir = tempfile.mkdtemp(prefix=u'make-double')

try:

    page = 0
    for format in layout.split():
        page += 1
        if format.endswith('w'):
            size = (297, 210)
            format = 'w'
        else:
            size = (210, 297)
            format = 'n'
        name = '%02u%s' % (page, format)
        im = Image.new('RGB', size, color=WHITE)
        draw = ImageDraw.Draw(im)
        draw.rectangle([20, 20] + [d - 20 for d in size], outline=BLACK)
        draw.text((40, 40), name, fill=BLACK)
        im.save('%s/%s.png' % (tmpdir, name))

    subprocess.check_call(['zip', '-j', '-r', archive, tmpdir])


finally:
    shutil.rmtree(tmpdir)
```

With your example, the result are:

- going forward: `1n 2w 3n+4n 5n 6w 7n`
- and backward from there: `7n 6w 4n+5n 3n+4n 2w 1n`

Both results are consistent with MComix 1.00, so the regressions are fixed.

For now, let's concentrate on the forward case. I think the results make sense, but you would like MComix to do this instead `1n 2w 3n+4n 4n+5n 6w 7n`?

**Comment by rathsky** [comment] 2015-09-23 14:31
Yes to all of that. I think MComix should maintain the selected double-page view as long as possible, and/or be consistent in both directions.

The only setting for "Show only one page were appropriate" where the current forward behavior is sensible IMHO is "Always", though other than that I can't discern what the intended difference between that setting and "Only for wide images" is.

**Comment by benoit-pierre** [comment] 2015-09-23 14:50
> Yes to all of that. I think MComix should maintain the selected double-page view as long as possible, and/or be consistent in both directions.

I think the results when going forward are fine as it is, because there is no point in showing a page that has already been read a second time, so the "3n+4n 5n 6w" transition is logical. If there is one case that could be improved, it's in fact the backward case: it should ideally be "6w 4n+5n 3n 2w" instead of the current "6w 4n+5n 3n+4n 2w" behaviour.

> The only setting for "Show only one page were appropriate" where the current forward behavior is sensible IMHO is "Always", though other than that I can't discern what the intended difference between that setting and "Only for wide images" is.

The difference is the behaviour on the first page. (Although it does not have an impact in your sample case because the second page is wide)

**Comment by rathsky** [comment] 2015-09-23 15:00
> I think the results when going forward are fine as it is, because there is no point in showing a page that has already been read a second time, so the "3n+4n 5n 6w" transition is logical.

That's where we disagree, I think the point is in the user having chosen both double-page mode and to be shown one picture only when that one is wide. The latter condition doesn't apply.

--

BTW, one currently gets another similar issue (IMO inconsistency) with those settings with (at least) two narrow pages:

Opening the first, both are shown – ok. Pressing End shows only the last – wrong, it should show the final two pages (ie. in this particular case, stay the same)…

… except when a) "Always" is selected and b) the final sequence of narrow images (that this image is part of) is of uneven count.

Behavior when opening the last image and pressing Pos1 is exactly the other way around.

**Comment by benoit-pierre** [comment] 2015-09-23 15:23
The thing is most archives will follow the layout of a physical book, so the first page is the cover, and a "double page" (whether a wide image that would have been 2 adjacent pages on the physical version or 2 pages meant to be shown together) will always occurs on a even+odd combination.

Anyway, it's not going to be possible to be always consistent, because we don't always know the full layout of the book, so depending on where you start, and the direction, you'll get a different sequence of pages.

I'm going to close this bug again: the regressions with respect to MComix 1.00 have been fixed. I'm going to look at a related bug (already present in 1.00): when backing out to an archive ending with "w n" pages, the wide page is shown, instead of the last page.

Regarding the way you think double page mode should work, I suggest you open a feature/bug request on the official bug tracker so other MComix developers can chime in.

**Closed** 2015-09-23 15:25 UTC
